### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by qlxi** [MeViMo/youbit#10]
I get an error, before that I uploaded this video and everything was fine and now this error
`python -m youbit download https://youtu.be/0V-R12BKWiI
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/__main__.py", line 212, in <module>
    main()
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/__main__.py", line 208, in main
    app()
  File "/home/qlxi/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/qlxi/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/qlxi/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/qlxi/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qlxi/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qlxi/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/qlxi/.local/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/__main__.py", line 174, in decode_url
    output_path = download_and_decode(url, output_dir)
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/decode.py", line 23, in download_and_decode
    downloader.download(download_path)
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/download.py", line 49, in download
    ydl.download([self.url])
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3318, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3293, in wrapper
    res = func(*args, **kwargs)
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1466, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/qlxi/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2682, in process_video_result
    formats_to_download = list(format_selector({
  File "/home/qlxi/.local/lib/python3.10/site-packages/youbit/download.py", line 62, in _format_selector
    resolution: tuple = self.youbit_metadata.settings.resolution.value
AttributeError: 'dict' object has no attribute 'settings'
`

**Comment by MeViMo** [comment]
I'm suspecting you upgraded to YouBit 2.0.0, but the video you're trying to decode was made with YouBit < 2.x. They are not compatible. Either decode with an earlier version of YouBit, or update the video's description to the following:
`gASVWwEAAAAAAACMD3lvdWJpdC5tZXRhZGF0YZSMCE1ldGFkYXRhlJOUKYGUfZQojAhmaWxlbmFtZZSMCHByaXYuemlwlIwIbWQ1X2hhc2iUjCBmMTI2MWRhZWNlOWM3MjdjNWUwZDY5NmRiODkxM2NkNZSMCV9zZXR0aW5nc5SMD3lvdWJpdC5zZXR0aW5nc5SMCFNldHRpbmdzlJOUKYGUfZQojAtfcmVzb2x1dGlvbpRoCowKUmVzb2x1dGlvbpSTlE2AB004BIaUhZRSlIwPX2JpdHNfcGVyX3BpeGVslGgKjAxCaXRzUGVyUGl4ZWyUk5RLAYWUUpSMDF9lY2Nfc3ltYm9sc5RLIIwVX2NvbnN0YW50X3JhdGVfZmFjdG9ylEsSjAxfbnVsbF9mcmFtZXOUiYwIX2Jyb3dzZXKUTnVijA55b3ViaXRfdmVyc2lvbpSMC3ByZWhpc3RvcmljlHViLg==`
This is the metadata of your video, but updated to be in the YouBit 2.x format. Note that the video will then be incompatible with earlier versions.

**Comment by qlxi** [comment]
> I'm suspecting you upgraded to YouBit 2.0.0, but the video you're trying to decode was made with YouBit < 2.x. They are not compatible. Either decode with an earlier version of YouBit, or update the video's description to the following: `gASVWwEAAAAAAACMD3lvdWJpdC5tZXRhZGF0YZSMCE1ldGFkYXRhlJOUKYGUfZQojAhmaWxlbmFtZZSMCHByaXYuemlwlIwIbWQ1X2hhc2iUjCBmMTI2MWRhZWNlOWM3MjdjNWUwZDY5NmRiODkxM2NkNZSMCV9zZXR0aW5nc5SMD3lvdWJpdC5zZXR0aW5nc5SMCFNldHRpbmdzlJOUKYGUfZQojAtfcmVzb2x1dGlvbpRoCowKUmVzb2x1dGlvbpSTlE2AB004BIaUhZRSlIwPX2JpdHNfcGVyX3BpeGVslGgKjAxCaXRzUGVyUGl4ZWyUk5RLAYWUUpSMDF9lY2Nfc3ltYm9sc5RLIIwVX2NvbnN0YW50X3JhdGVfZmFjdG9ylEsSjAxfbnVsbF9mcmFtZXOUiYwIX2Jyb3dzZXKUTnVijA55b3ViaXRfdmVyc2lvbpSMC3ByZWhpc3RvcmljlHViLg==` This is the metadata of your video, but updated to be in the YouBit 2.x format. Note that the video will then be incompatible with earlier versions.

`Traceback (most recent call last):
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\WORK\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\WORK\Downloads\youbit-0.1.4\youbit-0.1.4\youbit\__init__.py", line 10, in <module>
    from .yb import Encoder, Decoder
  File "C:\Users\WORK\Downloads\youbit-0.1.4\youbit-0.1.4\youbit\yb.py", line 19, in <module>
    import youbit.ecc.ecc as youbit_ecc
  File "C:\Users\WORK\Downloads\youbit-0.1.4\youbit-0.1.4\youbit\ecc\ecc.py", line 4, in <module>
    from youbit.ecc.creedsolo import RSCodec
ModuleNotFoundError: No module named 'youbit.ecc.creedsolo'`

**Comment by MeViMo** [comment]
That is another issue entirely. Your C extension was not compiled. Run `build.py`.
