### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by dszubov** [MeViMo/youbit#19]
made a video, uploaded it to youtube, then tried to decode and got error:

```
# python -m youbit download https://www.youtube.com/watch?v=somevideoid
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3523, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 668, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [youtube] somevideoid: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/youbit/youbit/__main__.py", line 212, in <module>
    main()
  File "/youbit/youbit/__main__.py", line 208, in main
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/youbit/youbit/__main__.py", line 174, in decode_url
    output_path = download_and_decode(url, output_dir)
  File "/youbit/youbit/decode.py", line 20, in download_and_decode
    downloader = Downloader(url)
  File "/youbit/youbit/download.py", line 23, in __init__
    self.video_metadata = self._get_video_metadata()
  File "/youbit/youbit/download.py", line 54, in _get_video_metadata
    video_metadata = ydl.extract_info(self.url, download=False)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] somevideoid: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by flonle** [comment]
Sorry, this repo is no longer maintained. I would suggest doing the upload and download manually, since that is the part that is (most likely) no longer working correctly. The actual encoding/decoding has a much better chance of still working today.
