### ISSUE TITLE
Support for 8k resolution videos 

### ISSUE THREAD

**Issue by LinuxUserGD** [MeViMo/youbit#7]
Currently decoding fails with
```bash
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/youbit/__main__.py", line 226, in decode_url
    filepath = decoder.decode(output)
  File "/home/user/.local/lib/python3.10/site-packages/youbit/yb.py", line 338, in decode
    with youbit.video.VideoDecoder(vid=file, zero_frame=zero_frame) as decoder:
  File "/home/user/.local/lib/python3.10/site-packages/youbit/video.py", line 169, in __init__
    raise RuntimeError(
RuntimeError: Unsupported codec: libdav1d
```

**Comment by MeViMo** [comment]
Adding support for the `dav1d` codec might be trivial or not so much depending on the GOP structure.
Might look into this sometime.
